version: '3.7'

# Define the services/containers to be run
services:
  database: # name of the service
    image: mongo # specify image to build container from
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    networks:
      - mongonetwork
  zup-testes:
  #name of your service
    build: ./
    # specify the directory of the Dockerfile
    # image: rlacruz/zuptest
    ports:
      - "3001:3000" #specify ports forwarding
    links:
      - database # link this service to the database service
    volumes:
      - ./data:/home/node/app/data
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: MongoDB2019!
    restart: on-failure
    depends_on:
      - database
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: teste
      ME_CONFIG_BASICAUTH_PASSWORD: teste
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_SERVER: 'database'
    links:
      - database
    networks:
      - mongonetwork
    restart: on-failure
networks:
  mongonetwork:
    # use a custom driver, with no options
    driver: bridge
