
version: '3'

services:
  #Container zup-testes
  zup-testes:
  #name of your service
    build: ./
    # specify the directory of the Dockerfile
    # image: rlacruz/zuptest
    ports:
      - "3001:3000" #specify ports forwarding
    links:
      - mongo # link this service to the database service
    volumes:
      - ./data:/home/node/app/data
    # environment:
    #   MONGO_USERNAME: root
    #   MONGO_PASSWORD: MongoDB2019!
    restart: on-failure
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: test
      ME_CONFIG_BASICAUTH_PASSWORD: test!
      ME_CONFIG_MONGODB_PORT: 27017
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
